name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check formatting
        run: |
          files=$(go run golang.org/x/tools/cmd/goimports@latest -l -local "github.com/G-Research" .)
          if [[ $files != "" ]]; then
            echo "Files need goimports running on them:"
            echo "$files"
            exit 1
          fi

      - name: Run tests
        run: |
          go test ./...
